"""added language coloum and remover program id

Revision ID: 1a37e8b60ed5
Revises: dccf93efd4ee
Create Date: 2024-07-22 07:34:45.536951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a37e8b60ed5'
down_revision = 'dccf93efd4ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.drop_column('program_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.add_column(sa.Column('program_id', sa.TEXT(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
